framework:
    cache:
        prefix_used: 'signalist/v1'

        app: cache.adapter.filesystem

        pools:
            # Tag-aware pool for every cache in the application
            signalist.cache:
                adapter: cache.app
                tags: true
                default_lifetime: 300
when@prod:
    framework:
        cache:
            pools:
                signalist.cache:
                    adapter: cache.adapter.redis_tag_aware
                    provider: '%env(REDIS_URL)'
                    default_lifetime: 300
